package com.cms.entity;

import java.io.Serializable;

public class CourseInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.Dec
     *
     * @mbg.generated
     */
    private String dec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.ID
     *
     * @return the value of course_info.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.ID
     *
     * @param id the value for course_info.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.Name
     *
     * @return the value of course_info.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.Name
     *
     * @param name the value for course_info.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.Dec
     *
     * @return the value of course_info.Dec
     *
     * @mbg.generated
     */
    public String getDec() {
        return dec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.Dec
     *
     * @param dec the value for course_info.Dec
     *
     * @mbg.generated
     */
    public void setDec(String dec) {
        this.dec = dec == null ? null : dec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", dec=").append(dec);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}