package com.cms.dao;

import com.cms.entity.ClassroomInfo;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface ClassroomInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_info
     *
     * @mbg.generated
     */
    int insert(ClassroomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_info
     *
     * @mbg.generated
     */
    ClassroomInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_info
     *
     * @mbg.generated
     */
    List<ClassroomInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClassroomInfo record);
}