package com.cms.dao;

import com.cms.entity.CourseInfo;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface CourseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated
     */
    int insert(CourseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated
     */
    CourseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated
     */
    List<CourseInfo> selectAll( CourseInfo courseInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CourseInfo record);
}